project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "Hands-on_Ex/**/*.qmd"
    - "In-class_Ex/**/*.qmd"
    - "Take-home_Ex/**/*.qmd"
    # Keep the original in-class draft without publishing it.
    - "!InclassEx/InClassEx4.qmd"

website:
  title: "ISSS626-GAA | Bao Sihan"

  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1A"
            href: Hands-on_Ex/Hands-on_Ex01A/Hands-on_Ex01A.qmd
          - text: "Hands-on Exercise 1B"
            href: Hands-on_Ex/Hands-on_Ex01B/Hands-on_Ex01B.qmd
          - text: "Hands-on Exercise 2A"
            href: Hands-on_Ex/Hands-on_Ex02A/Hands-on_Ex02A.qmd
          - text: "Hands-on Exercise 2B"
            href: Hands-on_Ex/Hands-on_Ex02B/Hands-on_Ex02B.qmd
          - text: "Hands-on Exercise 4"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.qmd
          - text: "In Class Exercise 4"
            href: In-class_Ex/In-class_Ex04/In-class_Ex04.qmd
      - text: "Take-Home Exercise"
        menu:
          - text: "Overview"
            href: take-home.html
          - text: "Take-Home Exercise 1"
            href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd

    right:
      - href: index.html
        text: Home
      - href: about.html
        text: About

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    code-fold: false

editor: visual
