project:
  type: website
  output-dir: _site

website:
  title: "ISSS626-GAA | Bao Sihan"

  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1A"
            href: Hands-on_Ex/Hands-on_Ex01A/Hands-on_Ex01A.qmd
          - text: "Hands-on Exercise 1B"
            href: Hands-on_Ex/Hands-on_Ex01B/Hands-on_Ex01B.qmd
          - text: "Hands-on Exercise 2A"
            href: Hands-on_Ex/Hands-on_Ex02A/Hands-on_Ex02A.qmd
          - text: "Hands-on Exercise 2B"
            href: Hands-on_Ex/Hands-on_Ex02B/Hands-on_Ex02B.qmd
      - text: "Take-Home Exercise"
        menu:
          - text: "Overview"
            href: take-home.html

    right:
      - href: index.html
        text: Home
      - href: about.html
        text: About

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    code-fold: false

editor: visual
