<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bao Sihan">

<title>Exploring Thermal Detections in Kapuas Regency – ISSS626-GAA | Bao Sihan</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-92404dd89b1444827012a9e3a58cda88.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626-GAA | Bao Sihan</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01A/Hands-on_Ex01A.html">
 <span class="dropdown-text">Hands-on Exercise 1A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01B/Hands-on_Ex01B.html">
 <span class="dropdown-text">Hands-on Exercise 1B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02A/Hands-on_Ex02A.html">
 <span class="dropdown-text">Hands-on Exercise 2A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02B/Hands-on_Ex02B.html">
 <span class="dropdown-text">Hands-on Exercise 2B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html"> 
<span class="menu-text">In Class Exercise 4</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../take-home.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-Home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-and-research-questions" id="toc-introduction-and-research-questions" class="nav-link active" data-scroll-target="#introduction-and-research-questions"><span class="header-section-number">1</span> Introduction and research questions</a></li>
  <li><a href="#data-and-study-design" id="toc-data-and-study-design" class="nav-link" data-scroll-target="#data-and-study-design"><span class="header-section-number">2</span> Data and study design</a>
  <ul class="collapse">
  <li><a href="#sources-and-provenance" id="toc-sources-and-provenance" class="nav-link" data-scroll-target="#sources-and-provenance"><span class="header-section-number">2.1</span> Sources and provenance</a></li>
  <li><a href="#observation-unit-and-scope" id="toc-observation-unit-and-scope" class="nav-link" data-scroll-target="#observation-unit-and-scope"><span class="header-section-number">2.2</span> Observation unit and scope</a></li>
  <li><a href="#spatial-window-and-coordinates" id="toc-spatial-window-and-coordinates" class="nav-link" data-scroll-target="#spatial-window-and-coordinates"><span class="header-section-number">2.3</span> Spatial window and coordinates</a></li>
  </ul></li>
  <li><a href="#data-preparation-and-quality" id="toc-data-preparation-and-quality" class="nav-link" data-scroll-target="#data-preparation-and-quality"><span class="header-section-number">3</span> Data preparation and quality</a>
  <ul class="collapse">
  <li><a href="#coverage-is-not-continuous-observation" id="toc-coverage-is-not-continuous-observation" class="nav-link" data-scroll-target="#coverage-is-not-continuous-observation"><span class="header-section-number">3.1</span> Coverage is not continuous observation</a></li>
  </ul></li>
  <li><a href="#first-order-analysis" id="toc-first-order-analysis" class="nav-link" data-scroll-target="#first-order-analysis"><span class="header-section-number">4</span> First-order analysis</a>
  <ul class="collapse">
  <li><a href="#detection-distribution" id="toc-detection-distribution" class="nav-link" data-scroll-target="#detection-distribution"><span class="header-section-number">4.1</span> Detection distribution</a></li>
  <li><a href="#monthly-distribution" id="toc-monthly-distribution" class="nav-link" data-scroll-target="#monthly-distribution"><span class="header-section-number">4.2</span> Monthly distribution</a></li>
  <li><a href="#kernel-density-estimation-and-bandwidth-sensitivity" id="toc-kernel-density-estimation-and-bandwidth-sensitivity" class="nav-link" data-scroll-target="#kernel-density-estimation-and-bandwidth-sensitivity"><span class="header-section-number">4.3</span> Kernel density estimation and bandwidth sensitivity</a></li>
  </ul></li>
  <li><a href="#second-order-analysis" id="toc-second-order-analysis" class="nav-link" data-scroll-target="#second-order-analysis"><span class="header-section-number">5</span> Second-order analysis</a>
  <ul class="collapse">
  <li><a href="#why-two-reference-patterns" id="toc-why-two-reference-patterns" class="nav-link" data-scroll-target="#why-two-reference-patterns"><span class="header-section-number">5.1</span> Why two reference patterns?</a></li>
  <li><a href="#what-the-comparison-does-not-establish" id="toc-what-the-comparison-does-not-establish" class="nav-link" data-scroll-target="#what-the-comparison-does-not-establish"><span class="header-section-number">5.2</span> What the comparison does not establish</a></li>
  </ul></li>
  <li><a href="#integrated-findings" id="toc-integrated-findings" class="nav-link" data-scroll-target="#integrated-findings"><span class="header-section-number">6</span> Integrated findings</a></li>
  <li><a href="#public-safety-planning-and-management" id="toc-public-safety-planning-and-management" class="nav-link" data-scroll-target="#public-safety-planning-and-management"><span class="header-section-number">7</span> Public-safety planning and management</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">8</span> Limitations</a></li>
  <li><a href="#reproducibility-and-review" id="toc-reproducibility-and-review" class="nav-link" data-scroll-target="#reproducibility-and-review"><span class="header-section-number">9</span> Reproducibility and review</a>
  <ul class="collapse">
  <li><a href="#preparation-code" id="toc-preparation-code" class="nav-link" data-scroll-target="#preparation-code"><span class="header-section-number">9.1</span> Preparation code</a></li>
  <li><a href="#analysis-code" id="toc-analysis-code" class="nav-link" data-scroll-target="#analysis-code"><span class="header-section-number">9.2</span> Analysis code</a></li>
  <li><a href="#software-versions" id="toc-software-versions" class="nav-link" data-scroll-target="#software-versions"><span class="header-section-number">9.3</span> Software versions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">10</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exploring Thermal Detections in Kapuas Regency</h1>
<p class="subtitle lead">Take-Home Exercise 1: Geospatial Analytics for Public Safety</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bao Sihan </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p><a href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">Exercise overview</a> · <a href="../../Take-home_Ex/Take-home_Ex01/executive-summary.html">Executive summary</a></p>
<section id="introduction-and-research-questions" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction-and-research-questions"><span class="header-section-number">1</span> Introduction and research questions</h2>
<p>In this exercise, I explore thermal detections in Kapuas Regency, Central Kalimantan, from 1 January to 31 August 2026. I use the first-order and second-order methods introduced in class to examine where the detections occur and how they are grouped. For the forest fire case in this assignment, the aim is to identify areas that deserve closer checking. Kapuas and the study period were selected before looking at the statistical results. Each point represents a satellite observation, so several points may come from the same fire.</p>
<p>Three questions guide the work:</p>
<ol type="1">
<li>Where and when are retained detections concentrated?</li>
<li>Are nearby detections more common than expected under uniform and spatially varying reference patterns?</li>
<li>What planning uses are supported, and what further evidence would be needed?</li>
</ol>
<p>After cleaning, <strong>6,515 detections</strong> remain, with <strong>96.5%</strong> recorded in August. The main density peak is on the western side of the county, near 2.0°S. These results mainly describe the activity observed in August; they do not establish the usual pattern for a whole year.</p>
</section>
<section id="data-and-study-design" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="data-and-study-design"><span class="header-section-number">2</span> Data and study design</h2>
<section id="sources-and-provenance" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="sources-and-provenance"><span class="header-section-number">2.1</span> Sources and provenance</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Input</th>
<th>Product and coverage</th>
<th>Provenance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Thermal anomalies</td>
<td>NASA FIRMS VIIRS S-NPP 375 m, Collection 2; Indonesia, Jan-Aug 2026</td>
<td>Request 804686; ZIP and both CSVs preserved; imported into this project on 14 September 2026 (Singapore time)</td>
</tr>
<tr class="even">
<td>Administrative window</td>
<td>Kapuas, Kalimantan Tengah, code 62.03</td>
<td>BIG layer 13, object 526; metadata TASWIL5000020240905KABKOTA; retrieved on 13 September 2026 (Singapore time)</td>
</tr>
</tbody>
</table>
<p>I obtained the county polygon from BIG’s administrative boundary service, which is linked from the <a href="https://www.indonesia-geospasial.com/2023/05/download-shapefile-batas-administrasi.html">boundary source given in the assignment</a>. Source links, file checksums and acquisition details are saved in <code>_workflow/acquisition.json</code>. The BIG metadata does not state a redistribution licence; this needs checking before sharing the raw boundary file publicly.</p>
<p>FIRMS supplies standard/archive and near-real-time (NRT) records separately, replacing NRT records with standard processing as available. Combining their time periods requires retaining the source/version flag (<a href="https://firms.modaps.eosdis.nasa.gov/download/Readme.txt">NASA download README</a>).</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Actual file coverage, before filtering.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">source</th>
<th style="text-align: right;">rows</th>
<th style="text-align: left;">first</th>
<th style="text-align: left;">last</th>
<th style="text-align: right;">missing_type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">archive</td>
<td style="text-align: right;">20725</td>
<td style="text-align: left;">2026-01-01</td>
<td style="text-align: left;">2026-04-27</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">nrt</td>
<td style="text-align: right;">179073</td>
<td style="text-align: left;">2026-04-30</td>
<td style="text-align: left;">2026-08-31</td>
<td style="text-align: right;">179073</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="observation-unit-and-scope" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="observation-unit-and-scope"><span class="header-section-number">2.2</span> Observation unit and scope</h3>
<p>One observation is a nominal- or high-confidence S-NPP thermal detection at a reported coordinate and UTC acquisition date/time. A unique key combines satellite, date, time, latitude and longitude. Distinct observations at different times remain distinct, even if they may describe the same ongoing fire. No aggregation into incidents is attempted.</p>
<p>I use the same confidence filter for both files. The archive has a <code>type</code> field, but the NRT file does not. Among the retained records, 83 are labelled presumed vegetation fire, one is labelled another static land source, and 6,431 have no type information. I retain the static-source record because the study includes thermal detections regardless of type. Filtering only for vegetation fires would remove almost all later records simply because their type is missing. Without forest-cover data or verified incidents, I cannot describe all these detections as forest fires.</p>
<p>The confidence categories are algorithmic quality indicators, not probabilities that individual observations represent forest fires. Restricting to nominal/high confidence reduces lower-quality candidates but can omit real activity (<a href="https://forum.earthdata.nasa.gov/viewtopic.php?t=5182">NASA confidence guidance</a>). Field meanings and hotspot types follow the <a href="https://www.earthdata.nasa.gov/s3fs-public/2024-07/VIIRS_C2_AF-375m_User_Guide_1.0.pdf">VIIRS Collection 2 user guide</a>.</p>
</section>
<section id="spatial-window-and-coordinates" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="spatial-window-and-coordinates"><span class="header-section-number">2.3</span> Spatial window and coordinates</h3>
<p>The complete Kapuas polygon is the observation window, including locations without detections. Using a convex hull of the observed points would wrongly remove low-detection areas. The source polygon is a valid, nonempty polygon with a third coordinate dimension. The workflow removes Z/M and transforms both sources consistently to WGS84 before point-in-polygon filtering, including boundary points. For metric analysis, it uses WGS84 / UTM zone 50S (EPSG:32750), then rescales metres to kilometres for <code>spatstat</code>.</p>
<p>The projected county area is <strong>17,058.19 km²</strong>. Zone 50S is a practical regional metric projection around the county’s longitude; the western edge slightly crosses the nominal zone boundary. Distances are planar approximations. The exact polygon, rather than its bounding rectangle, defines all KDE and simulation windows.</p>
</section>
</section>
<section id="data-preparation-and-quality" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="data-preparation-and-quality"><span class="header-section-number">3</span> Data preparation and quality</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Sequential filtering audit for the Indonesia request.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">step</th>
<th style="text-align: right;">before</th>
<th style="text-align: right;">excluded</th>
<th style="text-align: right;">retained</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Valid coordinates</td>
<td style="text-align: right;">199798</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">199798</td>
</tr>
<tr class="even">
<td style="text-align: left;">Valid UTC date and time</td>
<td style="text-align: right;">199798</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">199798</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Study dates</td>
<td style="text-align: right;">199798</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">199798</td>
</tr>
<tr class="even">
<td style="text-align: left;">S-NPP satellite</td>
<td style="text-align: right;">199798</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">199798</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Duplicate observation key (archive first)</td>
<td style="text-align: right;">199798</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">199798</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nominal or high confidence</td>
<td style="text-align: right;">199798</td>
<td style="text-align: right;">8910</td>
<td style="text-align: right;">190888</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kapuas polygon (boundary included)</td>
<td style="text-align: right;">190888</td>
<td style="text-align: right;">184373</td>
<td style="text-align: right;">6515</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Both raw files contain 199,798 records in total. Required coordinates and timestamps are populated and valid, all observations fall within the requested dates, and no duplicate observation keys are present. If duplicate keys were present, the archive version would take precedence. At national level, 8,910 low-confidence records are removed. The polygon filter retains 6,515 observations; equivalently, the county contains 6,716 original records, of which 201 are low confidence. No retained observations have exactly identical spatial coordinates.</p>
<p>The missingness check treats the absent NRT <code>type</code> field separately from missing coordinates or dates. Acquisition times are kept in four-digit UTC format, including values such as 0513. The cleaning checks also confirm that observations at the same location on different dates are retained. This matters because a repeat observation is different from an accidentally duplicated row.</p>
<section id="coverage-is-not-continuous-observation" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="coverage-is-not-continuous-observation"><span class="header-section-number">3.1</span> Coverage is not continuous observation</h3>
<p>The national request has no records on 13 dates: 10-12 March, 28-29 April, 1 June, 11-16 July and 3 August. These are <strong>dates with no records</strong>, not verified fire-free days. The CSV files alone cannot tell us whether this reflects missing acquisitions, obscuration, processing gaps or no detected activity. I leave these dates as observed rather than filling in assumed counts. The April gap falls between the archive and NRT coverage. February’s zero county detections also does not establish that there were no fires.</p>
<p>Monthly rates use calendar days only; they do not correct for overpass availability or cloud-free observable area. Archive/NRT processing differences and missing dates weaken direct comparisons across months. An eight-month series does not establish annual seasonality.</p>
</section>
</section>
<section id="first-order-analysis" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="first-order-analysis"><span class="header-section-number">4</span> First-order analysis</h2>
<section id="detection-distribution" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="detection-distribution"><span class="header-section-number">4.1</span> Detection distribution</h3>
<div id="fig-detections" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Map of retained satellite detections within Kapuas.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-detections-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="output/figures/detections.png" class="img-fluid figure-img" style="width:75.0%" alt="Map of retained satellite detections within Kapuas.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-detections-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Retained thermal detections within the Kapuas administrative window.
</figcaption>
</figure>
</div>
<p><strong>Map interpretation.</strong> Detections form several dense groups rather than filling Kapuas evenly. Groups are visible around 1.2-1.6°S, along the western side near 2.0-2.2°S, and toward the southeast around 2.5-2.7°S. Northern and far-southern areas contain fewer detections. Point overlap hides the number of observations in dense groups, motivating KDE. The map identifies concentration in the retained observations, not the area burned, number of incidents, land-cover category or population at risk.</p>
</section>
<section id="monthly-distribution" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="monthly-distribution"><span class="header-section-number">4.2</span> Monthly distribution</h3>
<div id="fig-monthly" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Monthly detection totals with August clearly dominant.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-monthly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="output/figures/monthly.png" class="img-fluid figure-img" alt="Monthly detection totals with August clearly dominant.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-monthly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Monthly totals after the same quality and spatial filters.
</figcaption>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Calendar-day rates are descriptive, not observation-adjusted rates.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">month</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">calendar_days</th>
<th style="text-align: right;">per_calendar_day</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2026-01</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">2.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">2026-02</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2026-03</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0.23</td>
</tr>
<tr class="even">
<td style="text-align: left;">2026-04</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2026-05</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0.23</td>
</tr>
<tr class="even">
<td style="text-align: left;">2026-06</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2026-07</td>
<td style="text-align: right;">119</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">3.84</td>
</tr>
<tr class="even">
<td style="text-align: left;">2026-08</td>
<td style="text-align: right;">6290</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">202.90</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>August contains 6,290 of 6,515 detections, compared with 119 in July and no more than 62 in any earlier month. This large observed contrast is the dominant temporal result. It motivates closer inspection of the August activity period, while the coverage limitations prevent attributing the entire change to a change in fire occurrence. Most retained records use NRT processing, so the results should be revisited when standard data for the same period become available.</p>
</section>
<section id="kernel-density-estimation-and-bandwidth-sensitivity" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="kernel-density-estimation-and-bandwidth-sensitivity"><span class="header-section-number">4.3</span> Kernel density estimation and bandwidth sensitivity</h3>
<p>For an event pattern with coordinates <span class="math inline">\(x_i\)</span>, a Gaussian kernel estimates intensity as a spatially smoothed sum of contributions from nearby detections. <code>density.ppp()</code> corrects for kernel mass outside the window. The result has units of <strong>detections per square kilometre over the study period</strong>, not an annual rate or a probability.</p>
<p>I use <strong>5 km Gaussian sigma</strong> for the main map. This smooths the individual detections while keeping local concentrations visible at the county scale. It is a chosen display scale, not a statistically optimised bandwidth. I then double sigma to <strong>10 km</strong> to see whether the main pattern changes. Both maps use a 0.5 km grid, the same window and the same colour scale. The grid makes the surface easier to display; it does not make the observations accurate to 500 m.</p>
<div id="fig-kde" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two KDE maps comparing bandwidths while retaining the main western peak.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kde-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="output/figures/kde.png" class="img-fluid figure-img" alt="Two KDE maps comparing bandwidths while retaining the main western peak.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kde-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Gaussian KDE at 5 km and 10 km sigma using a shared intensity scale.
</figcaption>
</figure>
</div>
<p><strong>Map interpretation.</strong> Both bandwidths identify the western concentration near 2.0°S as the main feature. The 5 km surface separates several secondary concentrations; the 10 km surface lowers and merges peaks. The maximum 5 km intensity is 9.83 detections/km². Cell ranks across the two surfaces have Spearman correlation 0.912, supporting broad agreement without implying that peak boundaries are fixed. A peak close to the county edge is particularly sensitive to the observation window: neighbouring activity outside Kapuas is excluded.</p>
</section>
</section>
<section id="second-order-analysis" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="second-order-analysis"><span class="header-section-number">5</span> Second-order analysis</h2>
<section id="why-two-reference-patterns" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="why-two-reference-patterns"><span class="header-section-number">5.1</span> Why two reference patterns?</h3>
<p>KDE describes <strong>first-order intensity</strong>, or how the expected number of detections varies by location. The second question is whether detections have more neighbours than expected at different distances. I use Ripley’s K, expressed as <span class="math inline">\(L(r)=\sqrt{K(r)/\pi}\)</span>, because L makes departures from the random reference easier to read in distance units. Under homogeneous complete spatial randomness (CSR), <span class="math inline">\(L(r)-r\)</span> is expected near zero. A positive departure can reflect varying intensity, repeated observations of the same activity or dependence between events; it does not identify fire spread on its own.</p>
<p>The main classroom analysis uses translation edge correction and distances from 0 to 10 km at 0.1 km intervals. The 10 km upper limit emphasises local structure and limits, but does not eliminate, instability from the long narrow window. Distances below the approximate 375 m pixel scale should not be interpreted physically. Translation correction compensates for the observable overlap of the window for each point-pair displacement.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Reference</th>
<th>Simulation design</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Homogeneous CSR, conditional on count</td>
<td>199 independent patterns of 6,515 uniform points in Kapuas; seed 6262026</td>
<td>Tests the adequacy of spatial uniformity as a descriptive baseline</td>
</tr>
<tr class="even">
<td>Inhomogeneous, conditional on count</td>
<td>199 independent patterns drawn from the 10 km KDE intensity; seed 6262027</td>
<td>Checks residual pair structure relative to a specified smooth spatial-intensity model</td>
</tr>
</tbody>
</table>
<p>For the second reference, <code>Kinhom()</code> adjusts the contribution of each pair using the estimated intensity around its points. I estimate this intensity with a 10 km kernel, leaving out the point being evaluated so that it does not contribute to its own estimate. The same procedure is repeated <strong>for every simulated pattern</strong> before converting K to L. All simulations keep the observed count of 6,515 and change only the locations. Because the surface used to generate the simulations was itself estimated from the data, I treat this comparison as a check against one smooth spatial model, rather than a formal test with a known error rate.</p>
<p>The envelope is the minimum and maximum of 199 simulated curves at each distance. Under an exchangeable simple reference, its nominal pointwise coverage is about 99%; it is <strong>not a simultaneous 99% band</strong> over all distances. No global p-value is claimed. This distinction matters because inspecting many distances increases the chance of crossing a pointwise band. The relevant methods are documented in the installed <code>spatstat.explore</code> help for <code>Lest</code>, <code>Kinhom</code>, <code>density.ppp</code> and <code>envelope</code> (<a href="https://spatstat.org/">spatstat project</a>).</p>
<div id="fig-l" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Observed L curves exceed the uniform and varying intensity reference envelopes.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-l-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="output/figures/l-functions.png" class="img-fluid figure-img" alt="Observed L curves exceed the uniform and varying intensity reference envelopes.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-l-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Observed L minus r and pointwise simulation envelopes.
</figcaption>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Selected distances: observed and reference limits for L(r)-r, in km.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">r</th>
<th style="text-align: right;">observed</th>
<th style="text-align: right;">lower</th>
<th style="text-align: right;">upper</th>
<th style="text-align: left;">reference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.323</td>
<td style="text-align: right;">-0.028</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: left;">CSR</td>
</tr>
<tr class="even">
<td style="text-align: left;">51</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">12.814</td>
<td style="text-align: right;">-0.031</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: left;">CSR</td>
</tr>
<tr class="odd">
<td style="text-align: left;">101</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">13.981</td>
<td style="text-align: right;">-0.058</td>
<td style="text-align: right;">0.089</td>
<td style="text-align: left;">CSR</td>
</tr>
<tr class="even">
<td style="text-align: left;">112</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.261</td>
<td style="text-align: right;">-0.106</td>
<td style="text-align: right;">0.039</td>
<td style="text-align: left;">Inhomogeneous reference</td>
</tr>
<tr class="odd">
<td style="text-align: left;">152</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.879</td>
<td style="text-align: right;">-0.298</td>
<td style="text-align: right;">-0.099</td>
<td style="text-align: left;">Inhomogeneous reference</td>
</tr>
<tr class="even">
<td style="text-align: left;">202</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">-0.140</td>
<td style="text-align: right;">-0.574</td>
<td style="text-align: right;">-0.281</td>
<td style="text-align: left;">Inhomogeneous reference</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Figure interpretation.</strong> Both observed curves are above their reference envelopes from 0.5 to 10 km. At 5 km, L(r)-r is 12.814 km under CSR and 1.879 km after adjusting for intensity, showing that the choice of reference matters. At 10 km, the adjusted value is negative (-0.140 km), but it is still above the upper simulated limit (-0.281 km). I therefore compare it with the simulated band, rather than reading the zero line alone as evidence of inhibition. The remaining excess may reflect repeated detections or finer spatial differences, not necessarily interaction between separate fires.</p>
</section>
<section id="what-the-comparison-does-not-establish" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="what-the-comparison-does-not-establish"><span class="header-section-number">5.2</span> What the comparison does not establish</h3>
<p>These comparisons support excess local pair concentration relative to both specified references for the observed detection process. Even an excess after reweighting is not proof of interaction between distinct fires: a single extended or persistent fire can generate many nearby satellite detections, and a 10 km smooth intensity may omit finer environmental heterogeneity. The eight months are pooled, so the model does not separate spatial dependence from changing activity through time. No causal spread mechanism can be identified from these results.</p>
</section>
</section>
<section id="integrated-findings" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="integrated-findings"><span class="header-section-number">6</span> Integrated findings</h2>
<p>The point map and KDE provide consistent evidence of a geographically uneven observation pattern. The strong August concentration shows that the pooled maps largely represent that month’s detections. Bandwidth sensitivity preserves the main western concentration but alters the sharpness and separation of smaller peaks, so fine hotspot boundaries are not stable management zones.</p>
<p>The L curves add information about neighbouring detections across distances. The observed curves exceed both reference envelopes from 0.5 to 10 km, but the departure is much smaller after intensity adjustment. This shows why a uniform reference alone is not enough for this dataset. Even after the adjustment, repeated observations and finer environmental differences remain possible explanations. Taken together, the maps and curves identify places worth investigating, but they do not tell us how many separate fires occurred or who was exposed.</p>
</section>
<section id="public-safety-planning-and-management" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="public-safety-planning-and-management"><span class="header-section-number">7</span> Public-safety planning and management</h2>
<p>The main use I see is to help decide where to <strong>investigate further</strong>. The western concentration near 2.0°S and the smaller clusters could be checked against local incident records and recent imagery. The KDE provides a starting point for this review, but its contours change with bandwidth and should not be treated as exact management boundaries.</p>
<p>The large August count also suggests a reason to review the timing of preparedness and monitoring. It does not establish a recurring fire season. Comparing several years of consistently processed data, with information on satellite coverage, would provide a stronger basis for deciding when additional monitoring is needed.</p>
<p>Before recommending where to send resources, I would add settlements, important facilities, access routes and local response capacity. A place with many detections may not be the place with the greatest consequences for people. These data are needed before recommending a station location, an evacuation route or crew numbers.</p>
<p>Finally, a satellite alert should be checked before being communicated as a confirmed fire. These retrospective results can support planning discussions and field verification. Current emergency decisions need current information verified locally, consistent with the caution in the <a href="https://firms.modaps.eosdis.nasa.gov/download/Readme.txt">FIRMS disclaimer</a>.</p>
</section>
<section id="limitations" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="limitations"><span class="header-section-number">8</span> Limitations</h2>
<ul>
<li><strong>Detection process:</strong> satellite overpasses, obscuration, detection thresholds and repeated thermal observations affect counts. No denominator of observable area or acquisition opportunities is available.</li>
<li><strong>Classification:</strong> 98.7% of retained detections lack hotspot type; forest land cover and incident confirmation are absent. The analysis includes one known static-source detection.</li>
<li><strong>Temporal scope:</strong> January-August is not a full year. Thirteen national zero-record dates and mixed archive/NRT processing limit comparisons. August dominates the pooled spatial pattern.</li>
<li><strong>Spatial scale:</strong> the county boundary truncates neighbouring activity; the near-boundary KDE maximum deserves caution. Smoothing and projection choices affect detail, and 375 m denotes a nominal sensor pixel scale rather than exact event location.</li>
<li><strong>Statistical scope:</strong> envelopes are pointwise, and intensity-adjusted simulations rely on an estimated smooth surface. Residual excess can reflect fine heterogeneity and observation repetition. The analysis neither proves fire-to-fire interaction nor estimates causal drivers.</li>
<li><strong>Public safety:</strong> no population, damage, exposure or response-time data are included; detection intensity is not a risk measure.</li>
</ul>
</section>
<section id="reproducibility-and-review" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="reproducibility-and-review"><span class="header-section-number">9</span> Reproducibility and review</h2>
<p>A normal render of this report runs preparation and analysis from the saved raw files. The executive summary reads the resulting outputs. Run the following from this exercise directory with the recorded R packages available:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> tests/test-cleaning.R</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render technical-report.qmd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render executive-summary.qmd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Raw files are preserved in <code>data/raw</code>; prepared points/window and simulations are in <code>data/processed</code>; figures and tables are in <code>output</code>. Sources and checksums, seeds, bandwidths, simulation settings, execution logs and R session information are in <code>_workflow</code>. The code below specifies all cleaning and analytical transformations. No remote data refresh occurs during rendering.</p>
<p>For text-only revisions, <code>quarto render technical-report.qmd -P recompute:false</code> reuses the verified outputs. A fingerprint check rejects reuse if raw inputs, analytical scripts, tables, figures or processed results have changed. The default remains a complete recomputation.</p>
<section id="preparation-code" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="preparation-code"><span class="header-section-number">9.1</span> Preparation code</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>clean_records <span class="ot">&lt;-</span> <span class="cf">function</span>(d) {</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  required <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'latitude'</span>,<span class="st">'longitude'</span>,<span class="st">'acq_date'</span>,<span class="st">'acq_time'</span>,<span class="st">'satellite'</span>,<span class="st">'confidence'</span>,<span class="st">'source'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(<span class="fu">all</span>(required <span class="sc">%in%</span> <span class="fu">names</span>(d)))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="st">'type'</span> <span class="sc">%in%</span> <span class="fu">names</span>(d)) d<span class="sc">$</span>type <span class="ot">&lt;-</span> <span class="cn">NA_integer_</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  audit <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">step=</span><span class="fu">character</span>(),<span class="at">before=</span><span class="fu">integer</span>(),<span class="at">excluded=</span><span class="fu">integer</span>(),<span class="at">retained=</span><span class="fu">integer</span>())</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  keep <span class="ot">&lt;-</span> <span class="cf">function</span>(ok,label) {</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    ok[<span class="fu">is.na</span>(ok)] <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    audit <span class="ot">&lt;&lt;-</span> <span class="fu">rbind</span>(audit,<span class="fu">data.frame</span>(<span class="at">step=</span>label,<span class="at">before=</span><span class="fu">nrow</span>(d),<span class="at">excluded=</span><span class="fu">sum</span>(<span class="sc">!</span>ok),<span class="at">retained=</span><span class="fu">sum</span>(ok)))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    d <span class="ot">&lt;&lt;-</span> d[ok,,drop<span class="ot">=</span><span class="cn">FALSE</span>]</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  d<span class="sc">$</span>acq_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(d<span class="sc">$</span>acq_date,<span class="at">format=</span><span class="st">'%Y-%m-%d'</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  tm <span class="ot">&lt;-</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.integer</span>(d<span class="sc">$</span>acq_time))</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  d<span class="sc">$</span>acq_time <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">'%04d'</span>,tm)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">keep</span>(<span class="fu">is.finite</span>(d<span class="sc">$</span>latitude)<span class="sc">&amp;</span><span class="fu">abs</span>(d<span class="sc">$</span>latitude)<span class="sc">&lt;=</span><span class="dv">90</span> <span class="sc">&amp;</span> <span class="fu">is.finite</span>(d<span class="sc">$</span>longitude)<span class="sc">&amp;</span><span class="fu">abs</span>(d<span class="sc">$</span>longitude)<span class="sc">&lt;=</span><span class="dv">180</span>,<span class="st">'Valid coordinates'</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  tm <span class="ot">&lt;-</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.integer</span>(d<span class="sc">$</span>acq_time))</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">keep</span>(<span class="sc">!</span><span class="fu">is.na</span>(d<span class="sc">$</span>acq_date)<span class="sc">&amp;</span>tm<span class="sc">&gt;=</span><span class="dv">0</span><span class="sc">&amp;</span>tm<span class="sc">&lt;=</span><span class="dv">2359</span><span class="sc">&amp;</span>tm<span class="sc">%%</span><span class="dv">100</span><span class="sc">&lt;</span><span class="dv">60</span>,<span class="st">'Valid UTC date and time'</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">keep</span>(d<span class="sc">$</span>acq_date<span class="sc">&gt;=</span><span class="fu">as.Date</span>(<span class="st">'2026-01-01'</span>)<span class="sc">&amp;</span>d<span class="sc">$</span>acq_date<span class="sc">&lt;=</span><span class="fu">as.Date</span>(<span class="st">'2026-08-31'</span>),<span class="st">'Study dates'</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">keep</span>(d<span class="sc">$</span>satellite<span class="sc">==</span><span class="st">'SNPP'</span>,<span class="st">'S-NPP satellite'</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> d[<span class="fu">order</span>(<span class="fu">match</span>(d<span class="sc">$</span>source,<span class="fu">c</span>(<span class="st">'archive'</span>,<span class="st">'nrt'</span>))),,drop<span class="ot">=</span><span class="cn">FALSE</span>]</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  key <span class="ot">&lt;-</span> <span class="fu">paste</span>(d<span class="sc">$</span>latitude,d<span class="sc">$</span>longitude,d<span class="sc">$</span>acq_date,d<span class="sc">$</span>acq_time,d<span class="sc">$</span>satellite,<span class="at">sep=</span><span class="st">'|'</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">keep</span>(<span class="sc">!</span><span class="fu">duplicated</span>(key),<span class="st">'Duplicate observation key (archive first)'</span>)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">keep</span>(d<span class="sc">$</span>confidence <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'n'</span>,<span class="st">'h'</span>),<span class="st">'Nominal or high confidence'</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">data=</span>d,<span class="at">audit=</span>audit)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({<span class="fu">library</span>(sf);<span class="fu">library</span>(dplyr);<span class="fu">library</span>(spatstat.geom)})</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">'R/cleaning.R'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>sources <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">c</span>(<span class="st">'archive'</span>,<span class="st">'nrt'</span>),<span class="cf">function</span>(s) {</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a> d <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">paste0</span>(<span class="st">'data/raw/fire_'</span>,s,<span class="st">'_SV-C2_804686.csv'</span>),<span class="at">colClasses=</span><span class="fu">c</span>(<span class="at">acq_time=</span><span class="st">'character'</span>,<span class="at">version=</span><span class="st">'character'</span>))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a> d<span class="sc">$</span>source <span class="ot">&lt;-</span> s; d<span class="sc">$</span>raw_row <span class="ot">&lt;-</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(d)); d</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(sources)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>profile <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(sources,<span class="cf">function</span>(d) <span class="fu">data.frame</span>(<span class="at">source=</span>d<span class="sc">$</span>source[<span class="dv">1</span>],<span class="at">rows=</span><span class="fu">nrow</span>(d),<span class="at">first=</span><span class="fu">min</span>(d<span class="sc">$</span>acq_date),<span class="at">last=</span><span class="fu">max</span>(d<span class="sc">$</span>acq_date),<span class="at">missing_type=</span><span class="cf">if</span>(<span class="st">'type'</span><span class="sc">%in%</span><span class="fu">names</span>(d))<span class="fu">sum</span>(<span class="fu">is.na</span>(d<span class="sc">$</span>type)) <span class="cf">else</span> <span class="fu">nrow</span>(d))))</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(profile,<span class="st">'output/tables/source-profile.csv'</span>,<span class="at">row.names=</span><span class="cn">FALSE</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>missingness <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">field=</span><span class="fu">names</span>(raw),<span class="at">missing=</span><span class="fu">vapply</span>(raw,<span class="cf">function</span>(x)<span class="fu">sum</span>(<span class="fu">is.na</span>(x)),<span class="fu">integer</span>(<span class="dv">1</span>)))</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(missingness,<span class="st">'output/tables/missingness.csv'</span>,<span class="at">row.names=</span><span class="cn">FALSE</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">clean_records</span>(raw)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(<span class="fu">st_zm</span>(<span class="fu">st_read</span>(<span class="st">'data/raw/kapuas_big_20240905.geojson'</span>,<span class="at">quiet=</span><span class="cn">TRUE</span>)),<span class="dv">4326</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">nrow</span>(b)<span class="sc">==</span><span class="dv">1</span>,<span class="fu">all</span>(<span class="fu">st_is_valid</span>(b)),<span class="sc">!</span><span class="fu">any</span>(<span class="fu">st_is_empty</span>(b)))</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(z<span class="sc">$</span>data,<span class="at">coords=</span><span class="fu">c</span>(<span class="st">'longitude'</span>,<span class="st">'latitude'</span>),<span class="at">crs=</span><span class="dv">4326</span>,<span class="at">remove=</span><span class="cn">FALSE</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>inside <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(p,b))<span class="sc">&gt;</span><span class="dv">0</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>audit <span class="ot">&lt;-</span> <span class="fu">rbind</span>(z<span class="sc">$</span>audit,<span class="fu">data.frame</span>(<span class="at">step=</span><span class="st">'Kapuas polygon (boundary included)'</span>,<span class="at">before=</span><span class="fu">nrow</span>(p),<span class="at">excluded=</span><span class="fu">sum</span>(<span class="sc">!</span>inside),<span class="at">retained=</span><span class="fu">sum</span>(inside)))</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p[inside,]</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply type-neutral selection consistently to archive and NRT; retain known type flags for disclosure.</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(p,<span class="dv">32750</span>); b <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(b,<span class="dv">32750</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>xy <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(p)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>p<span class="sc">$</span>easting_m <span class="ot">&lt;-</span> xy[,<span class="dv">1</span>]; p<span class="sc">$</span>northing_m <span class="ot">&lt;-</span> xy[,<span class="dv">2</span>]</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>p<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">format</span>(p<span class="sc">$</span>acq_date,<span class="st">'%Y-%m'</span>)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">nrow</span>(p)<span class="sc">&gt;</span><span class="dv">30</span>,<span class="fu">all</span>(<span class="fu">st_is_valid</span>(p)),<span class="fu">all</span>(<span class="fu">lengths</span>(<span class="fu">st_intersects</span>(p,b))<span class="sc">&gt;</span><span class="dv">0</span>))</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(audit,<span class="st">'output/tables/cleaning-audit.csv'</span>,<span class="at">row.names=</span><span class="cn">FALSE</span>)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(<span class="fu">st_drop_geometry</span>(p),<span class="st">'data/processed/kapuas-detections.csv'</span>,<span class="at">row.names=</span><span class="cn">FALSE</span>)</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(<span class="fu">list</span>(<span class="at">points=</span>p,<span class="at">boundary=</span>b,<span class="at">audit=</span>audit,<span class="at">profile=</span>profile),<span class="st">'data/processed/prepared.rds'</span>)</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="fu">st_write</span>(p,<span class="st">'data/processed/kapuas.gpkg'</span>,<span class="at">layer=</span><span class="st">'detections'</span>,<span class="at">delete_layer=</span><span class="cn">TRUE</span>,<span class="at">quiet=</span><span class="cn">TRUE</span>)</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="fu">st_write</span>(b,<span class="st">'data/processed/kapuas.gpkg'</span>,<span class="at">layer=</span><span class="st">'boundary'</span>,<span class="at">delete_layer=</span><span class="cn">TRUE</span>,<span class="at">quiet=</span><span class="cn">TRUE</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>days <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">'2026-01-01'</span>),<span class="fu">as.Date</span>(<span class="st">'2026-08-31'</span>),<span class="at">by=</span><span class="st">'day'</span>)</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>coverage <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">date=</span>days,<span class="at">indonesia_records=</span><span class="fu">as.integer</span>(<span class="fu">table</span>(<span class="fu">factor</span>(<span class="fu">as.Date</span>(raw<span class="sc">$</span>acq_date),<span class="at">levels=</span>days))))</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(coverage,<span class="st">'output/tables/date-coverage.csv'</span>,<span class="at">row.names=</span><span class="cn">FALSE</span>)</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'Prepared'</span>,<span class="fu">nrow</span>(p),<span class="st">'detections; area'</span>,<span class="fu">as.numeric</span>(<span class="fu">st_area</span>(b))<span class="sc">/</span><span class="fl">1e6</span>,<span class="st">'km2</span><span class="sc">\n</span><span class="st">'</span>)</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(audit); <span class="fu">print</span>(<span class="fu">table</span>(p<span class="sc">$</span>month)); <span class="fu">cat</span>(<span class="st">'No Indonesia records on:'</span>,<span class="fu">as.character</span>(coverage<span class="sc">$</span>date[coverage<span class="sc">$</span>indonesia_records<span class="sc">==</span><span class="dv">0</span>]),<span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'Duplicate spatial coordinates:'</span>,<span class="fu">sum</span>(<span class="fu">duplicated</span>(<span class="fu">st_coordinates</span>(p))),<span class="st">'</span><span class="sc">\n</span><span class="st">'</span>);<span class="fu">print</span>(<span class="fu">table</span>(p<span class="sc">$</span>type,<span class="at">useNA=</span><span class="st">'always'</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="analysis-code" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="analysis-code"><span class="header-section-number">9.2</span> Analysis code</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({<span class="fu">library</span>(sf);<span class="fu">library</span>(dplyr);<span class="fu">library</span>(ggplot2);<span class="fu">library</span>(spatstat.geom);<span class="fu">library</span>(spatstat.explore);<span class="fu">library</span>(spatstat.random)})</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">'output/figures'</span>,<span class="at">showWarnings=</span><span class="cn">FALSE</span>,<span class="at">recursive=</span><span class="cn">TRUE</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">'data/processed/prepared.rds'</span>); p <span class="ot">&lt;-</span> z<span class="sc">$</span>points; b <span class="ot">&lt;-</span> z<span class="sc">$</span>boundary</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(<span class="fu">st_geometry</span>(b)); W <span class="ot">&lt;-</span> <span class="fu">rescale</span>(W,<span class="dv">1000</span>,<span class="at">unitname=</span><span class="fu">c</span>(<span class="st">'kilometre'</span>,<span class="st">'kilometres'</span>))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">ppp</span>(p<span class="sc">$</span>easting_m<span class="sc">/</span><span class="dv">1000</span>,p<span class="sc">$</span>northing_m<span class="sc">/</span><span class="dv">1000</span>,<span class="at">window=</span>W)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">npoints</span>(X)<span class="sc">==</span><span class="fu">nrow</span>(p),<span class="sc">!</span><span class="fu">any</span>(<span class="fu">duplicated</span>(X)))</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>params <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">seed=</span><span class="dv">6262026</span>L,<span class="at">nsim=</span><span class="dv">199</span>L,<span class="at">kde_sigma_km=</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">10</span>),<span class="at">pixel_km=</span><span class="fl">0.5</span>,<span class="at">r_km=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">10</span>,<span class="at">by=</span><span class="fl">0.1</span>),<span class="at">inhom_sigma_km=</span><span class="dv">10</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(params,<span class="st">'_workflow/parameters.rds'</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">writeLines</span>(<span class="fu">capture.output</span>(<span class="fu">str</span>(params)),<span class="st">'_workflow/parameters.txt'</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>(<span class="at">base_size=</span><span class="dv">12</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">panel.grid.minor=</span><span class="fu">element_blank</span>(),<span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">face=</span><span class="st">'bold'</span>),<span class="at">plot.title.position=</span><span class="st">'plot'</span>,<span class="at">plot.caption.position=</span><span class="st">'plot'</span>,<span class="at">plot.margin=</span><span class="fu">margin</span>(<span class="dv">12</span>,<span class="dv">12</span>,<span class="dv">12</span>,<span class="dv">12</span>),<span class="at">plot.caption=</span><span class="fu">element_text</span>(<span class="at">hjust=</span><span class="dv">0</span>,<span class="at">size=</span><span class="dv">9</span>)))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>save_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(g,name,<span class="at">w=</span><span class="dv">9</span>,<span class="at">h=</span><span class="dv">6</span>) <span class="fu">ggsave</span>(<span class="fu">paste0</span>(<span class="st">'output/figures/'</span>,name,<span class="st">'.png'</span>),g,<span class="at">width=</span>w,<span class="at">height=</span>h,<span class="at">dpi=</span><span class="dv">180</span>,<span class="at">bg=</span><span class="st">'white'</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>map <span class="ot">&lt;-</span> <span class="fu">ggplot</span>()<span class="sc">+</span><span class="fu">geom_sf</span>(<span class="at">data=</span>b,<span class="at">fill=</span><span class="st">'#edf1f3'</span>,<span class="at">colour=</span><span class="st">'#34495e'</span>,<span class="at">linewidth=</span>.<span class="dv">35</span>)<span class="sc">+</span><span class="fu">geom_sf</span>(<span class="at">data=</span>p,<span class="at">colour=</span><span class="st">'#d55129'</span>,<span class="at">alpha=</span>.<span class="dv">35</span>,<span class="at">size=</span>.<span class="dv">35</span>)<span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a> <span class="fu">labs</span>(<span class="at">title=</span><span class="st">'Thermal detections in Kapuas'</span>,<span class="at">subtitle=</span><span class="st">'VIIRS S-NPP | Jan-Aug 2026 | nominal/high confidence'</span>,<span class="at">x=</span><span class="cn">NULL</span>,<span class="at">y=</span><span class="cn">NULL</span>,<span class="at">caption=</span><span class="st">'Sources: NASA FIRMS request 804686; BIG boundary.</span><span class="sc">\n</span><span class="st">Each point represents a satellite detection.'</span>)<span class="sc">+</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a> <span class="fu">annotate</span>(<span class="st">'text'</span>,<span class="at">x=</span><span class="fu">st_bbox</span>(b)[<span class="st">'xmin'</span>]<span class="sc">+</span><span class="dv">13000</span>,<span class="at">y=</span><span class="fu">st_bbox</span>(b)[<span class="st">'ymax'</span>]<span class="sc">-</span><span class="dv">15000</span>,<span class="at">label=</span><span class="st">'N'</span>,<span class="at">size=</span><span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a> <span class="fu">annotate</span>(<span class="st">'segment'</span>,<span class="at">x=</span><span class="fu">st_bbox</span>(b)[<span class="st">'xmin'</span>]<span class="sc">+</span><span class="dv">5000</span>,<span class="at">xend=</span><span class="fu">st_bbox</span>(b)[<span class="st">'xmin'</span>]<span class="sc">+</span><span class="dv">55000</span>,<span class="at">y=</span><span class="fu">st_bbox</span>(b)[<span class="st">'ymin'</span>]<span class="sc">+</span><span class="dv">8000</span>,<span class="at">yend=</span><span class="fu">st_bbox</span>(b)[<span class="st">'ymin'</span>]<span class="sc">+</span><span class="dv">8000</span>,<span class="at">linewidth=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a> <span class="fu">annotate</span>(<span class="st">'text'</span>,<span class="at">x=</span><span class="fu">st_bbox</span>(b)[<span class="st">'xmin'</span>]<span class="sc">+</span><span class="dv">30000</span>,<span class="at">y=</span><span class="fu">st_bbox</span>(b)[<span class="st">'ymin'</span>]<span class="sc">+</span><span class="dv">17000</span>,<span class="at">label=</span><span class="st">'50 km'</span>,<span class="at">size=</span><span class="dv">3</span>)<span class="sc">+</span><span class="fu">theme</span>(<span class="at">axis.text.x=</span><span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">35</span>,<span class="at">hjust=</span><span class="dv">1</span>,<span class="at">size=</span><span class="dv">9</span>))</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="fu">save_plot</span>(map,<span class="st">'detections'</span>,<span class="dv">8</span>,<span class="dv">9</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>months <span class="ot">&lt;-</span> <span class="fu">format</span>(<span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">'2026-01-01'</span>),<span class="fu">as.Date</span>(<span class="st">'2026-08-01'</span>),<span class="at">by=</span><span class="st">'month'</span>),<span class="st">'%Y-%m'</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>monthly <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">month=</span>months,<span class="at">n=</span><span class="fu">as.integer</span>(<span class="fu">table</span>(<span class="fu">factor</span>(p<span class="sc">$</span>month,<span class="at">levels=</span>months))))</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>monthly<span class="sc">$</span>calendar_days <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">31</span>,<span class="dv">28</span>,<span class="dv">31</span>,<span class="dv">30</span>,<span class="dv">31</span>,<span class="dv">30</span>,<span class="dv">31</span>,<span class="dv">31</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>monthly<span class="sc">$</span>per_calendar_day <span class="ot">&lt;-</span> monthly<span class="sc">$</span>n<span class="sc">/</span>monthly<span class="sc">$</span>calendar_days</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(monthly,<span class="st">'output/tables/monthly.csv'</span>,<span class="at">row.names=</span><span class="cn">FALSE</span>)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(monthly,<span class="fu">aes</span>(month,n))<span class="sc">+</span><span class="fu">geom_col</span>(<span class="at">fill=</span><span class="st">'#d55129'</span>,<span class="at">width=</span>.<span class="dv">65</span>)<span class="sc">+</span><span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">format</span>(n,<span class="at">big.mark=</span><span class="st">','</span>)),<span class="at">vjust=</span><span class="sc">-</span>.<span class="dv">4</span>,<span class="at">size=</span><span class="fl">3.7</span>)<span class="sc">+</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_y_continuous</span>(<span class="at">expand=</span><span class="fu">expansion</span>(<span class="at">mult=</span><span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">12</span>)))<span class="sc">+</span><span class="fu">labs</span>(<span class="at">title=</span><span class="st">'August accounts for most retained detections'</span>,<span class="at">x=</span><span class="cn">NULL</span>,<span class="at">y=</span><span class="st">'Detection records'</span>,<span class="at">caption=</span><span class="st">'Zero denotes no retained detections, not proven absence of fire. Coverage and processing vary.'</span>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="fu">save_plot</span>(g,<span class="st">'monthly'</span>,<span class="dv">9</span>,<span class="dv">5</span>)</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>kd <span class="ot">&lt;-</span> <span class="fu">lapply</span>(params<span class="sc">$</span>kde_sigma_km,<span class="cf">function</span>(s) <span class="fu">density</span>(X,<span class="at">sigma=</span>s,<span class="at">eps=</span>params<span class="sc">$</span>pixel_km,<span class="at">edge=</span><span class="cn">TRUE</span>))</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>grids <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(<span class="fu">seq_along</span>(kd),<span class="cf">function</span>(i){d<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(kd[[i]]);<span class="fu">names</span>(d)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">'x'</span>,<span class="st">'y'</span>,<span class="st">'intensity'</span>);d<span class="sc">$</span>bandwidth<span class="ot">&lt;-</span><span class="fu">paste</span>(<span class="st">'Gaussian sigma ='</span>,params<span class="sc">$</span>kde_sigma_km[i],<span class="st">'km'</span>);d}))</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>bs <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(<span class="fu">as.polygonal</span>(W))</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(grids,<span class="fu">aes</span>(x,y,<span class="at">fill=</span>intensity))<span class="sc">+</span><span class="fu">geom_raster</span>()<span class="sc">+</span><span class="fu">geom_sf</span>(<span class="at">data=</span>bs,<span class="at">inherit.aes=</span><span class="cn">FALSE</span>,<span class="at">fill=</span><span class="cn">NA</span>,<span class="at">colour=</span><span class="st">'#34495e'</span>,<span class="at">linewidth=</span>.<span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_fill_viridis_c</span>(<span class="at">option=</span><span class="st">'inferno'</span>,<span class="at">name=</span><span class="st">'Detections / sq km'</span>,<span class="at">na.value=</span><span class="st">'white'</span>)<span class="sc">+</span><span class="fu">coord_sf</span>(<span class="at">datum=</span><span class="cn">NA</span>)<span class="sc">+</span><span class="fu">facet_wrap</span>(<span class="sc">~</span>bandwidth)<span class="sc">+</span></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a> <span class="fu">annotate</span>(<span class="st">'segment'</span>,<span class="at">x=</span><span class="dv">160</span>,<span class="at">xend=</span><span class="dv">210</span>,<span class="at">y=</span><span class="dv">9625</span>,<span class="at">yend=</span><span class="dv">9625</span>,<span class="at">linewidth=</span>.<span class="dv">8</span>,<span class="at">colour=</span><span class="st">'#cccccc'</span>)<span class="sc">+</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a> <span class="fu">annotate</span>(<span class="st">'text'</span>,<span class="at">x=</span><span class="dv">185</span>,<span class="at">y=</span><span class="dv">9632</span>,<span class="at">label=</span><span class="st">'50 km'</span>,<span class="at">colour=</span><span class="st">'#777777'</span>,<span class="at">size=</span><span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a> <span class="fu">labs</span>(<span class="at">title=</span><span class="st">'Detection intensity at two smoothing scales'</span>,<span class="at">subtitle=</span><span class="st">'Boundary-corrected Gaussian KDE; 500 m grid; north is up'</span>,<span class="at">x=</span><span class="cn">NULL</span>,<span class="at">y=</span><span class="cn">NULL</span>,<span class="at">caption=</span><span class="st">'Same colour scale across panels. Density measures observed detections, not burned area or risk.'</span>)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a><span class="fu">save_plot</span>(g,<span class="st">'kde'</span>,<span class="dv">10</span>,<span class="dv">9</span>)</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>main <span class="ot">&lt;-</span> kd[[<span class="dv">1</span>]]; broad <span class="ot">&lt;-</span> kd[[<span class="dv">2</span>]]</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>peak <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(main); peak <span class="ot">&lt;-</span> peak[<span class="fu">which.max</span>(peak<span class="sc">$</span>value),]</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(<span class="fu">as.vector</span>(main<span class="sc">$</span>v),<span class="fu">as.vector</span>(broad<span class="sc">$</span>v),<span class="at">use=</span><span class="st">'complete.obs'</span>,<span class="at">method=</span><span class="st">'spearman'</span>)</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>summary <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">n=</span><span class="fu">npoints</span>(X),<span class="at">area_km2=</span><span class="fu">area.owin</span>(W),<span class="at">august_share=</span>monthly<span class="sc">$</span>n[<span class="dv">8</span>]<span class="sc">/</span><span class="fu">sum</span>(monthly<span class="sc">$</span>n),<span class="at">kde_spearman=</span>correlation,<span class="at">kde_peak=</span>peak,<span class="at">known_static=</span><span class="fu">sum</span>(p<span class="sc">$</span>type<span class="sc">==</span><span class="dv">2</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>),<span class="at">unknown_type=</span><span class="fu">sum</span>(<span class="fu">is.na</span>(p<span class="sc">$</span>type)))</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(<span class="fu">list</span>(<span class="at">X=</span>X,<span class="at">kde=</span>kd,<span class="at">monthly=</span>monthly,<span class="at">summary=</span>summary),<span class="st">'data/processed/first-order.rds'</span>)</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'CP4A saved</span><span class="sc">\n</span><span class="st">'</span>);<span class="fu">print</span>(summary)</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Conditional-on-count CSR reference. Pointwise envelopes are explicitly labelled; no multiple-distance p-value is claimed.</span></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(params<span class="sc">$</span>seed)</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>csr <span class="ot">&lt;-</span> <span class="fu">envelope</span>(X,Lest,<span class="at">nsim=</span>params<span class="sc">$</span>nsim,<span class="at">simulate=</span><span class="fu">expression</span>(<span class="fu">runifpoint</span>(<span class="fu">npoints</span>(X),<span class="at">win=</span>W)),<span class="at">r=</span>params<span class="sc">$</span>r_km,<span class="at">correction=</span><span class="st">'translate'</span>,<span class="at">savefuns=</span><span class="cn">TRUE</span>,<span class="at">verbose=</span><span class="cn">FALSE</span>)</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(csr,<span class="st">'data/processed/csr-envelope.rds'</span>);<span class="fu">cat</span>(<span class="st">'CSR simulations saved</span><span class="sc">\n</span><span class="st">'</span>)</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Inhomogeneous binomial reference conditional on count and an estimated smooth intensity.</span></span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Reestimate the leave-one-out intensity for each simulated pattern at the same fixed bandwidth.</span></span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>L_adjusted <span class="ot">&lt;-</span> <span class="cf">function</span>(Y,r,...) {</span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a> lambda <span class="ot">&lt;-</span> <span class="fu">density</span>(Y,<span class="at">sigma=</span>params<span class="sc">$</span>inhom_sigma_km,<span class="at">at=</span><span class="st">'points'</span>,<span class="at">leaveoneout=</span><span class="cn">TRUE</span>,<span class="at">edge=</span><span class="cn">TRUE</span>)</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a> K <span class="ot">&lt;-</span> <span class="fu">Kinhom</span>(Y,<span class="at">lambda=</span>lambda,<span class="at">r=</span>r,<span class="at">correction=</span><span class="st">'translate'</span>)</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a> <span class="fu">eval.fv</span>(<span class="fu">sqrt</span>(K<span class="sc">/</span>pi))</span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(params<span class="sc">$</span>seed<span class="sc">+</span><span class="dv">1</span>L)</span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>inh <span class="ot">&lt;-</span> <span class="fu">envelope</span>(X,L_adjusted,<span class="at">nsim=</span>params<span class="sc">$</span>nsim,<span class="at">simulate=</span><span class="fu">expression</span>(<span class="fu">rpoint</span>(<span class="fu">npoints</span>(X),<span class="at">f=</span>broad,<span class="at">win=</span>W,<span class="at">forcewin=</span><span class="cn">TRUE</span>)),<span class="at">r=</span>params<span class="sc">$</span>r_km,<span class="at">savefuns=</span><span class="cn">TRUE</span>,<span class="at">verbose=</span><span class="cn">FALSE</span>)</span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(inh,<span class="st">'data/processed/inhom-envelope.rds'</span>);<span class="fu">cat</span>(<span class="st">'Inhomogeneous simulations saved</span><span class="sc">\n</span><span class="st">'</span>)</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>curves <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(<span class="fu">c</span>(<span class="st">'CSR'</span>,<span class="st">'Inhomogeneous reference'</span>),<span class="cf">function</span>(label){e<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(<span class="cf">if</span>(label<span class="sc">==</span><span class="st">'CSR'</span>)csr <span class="cf">else</span> inh);<span class="fu">data.frame</span>(<span class="at">r=</span>e<span class="sc">$</span>r,<span class="at">observed=</span>e<span class="sc">$</span>obs<span class="sc">-</span>e<span class="sc">$</span>r,<span class="at">lower=</span>e<span class="sc">$</span>lo<span class="sc">-</span>e<span class="sc">$</span>r,<span class="at">upper=</span>e<span class="sc">$</span>hi<span class="sc">-</span>e<span class="sc">$</span>r,<span class="at">reference=</span>label)}))</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(curves,<span class="st">'output/tables/l-curves.csv'</span>,<span class="at">row.names=</span><span class="cn">FALSE</span>)</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(curves,<span class="fu">aes</span>(r,observed))<span class="sc">+</span><span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>lower,<span class="at">ymax=</span>upper),<span class="at">fill=</span><span class="st">'#bdcbd3'</span>,<span class="at">alpha=</span>.<span class="dv">7</span>)<span class="sc">+</span><span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>,<span class="at">linetype=</span><span class="dv">2</span>,<span class="at">colour=</span><span class="st">'#555555'</span>)<span class="sc">+</span><span class="fu">geom_line</span>(<span class="at">colour=</span><span class="st">'#d55129'</span>,<span class="at">linewidth=</span>.<span class="dv">9</span>)<span class="sc">+</span><span class="fu">facet_wrap</span>(<span class="sc">~</span>reference,<span class="at">scales=</span><span class="st">'free_y'</span>)<span class="sc">+</span></span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a> <span class="fu">labs</span>(<span class="at">title=</span><span class="st">'Pair structure relative to two spatial reference patterns'</span>,<span class="at">subtitle=</span><span class="st">'Translation correction | 199 simulations | conditional on 6,515 points'</span>,<span class="at">x=</span><span class="st">'Distance r (km)'</span>,<span class="at">y=</span><span class="st">'L(r) - r (km)'</span>,<span class="at">caption=</span><span class="st">'Grey: pointwise min-max reference envelope (~99% at each distance). Panels have different y scales.</span><span class="sc">\n</span><span class="st">Inhomogeneous envelope is an estimated-intensity diagnostic, not a calibrated global significance test.'</span>)</span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a><span class="fu">save_plot</span>(g,<span class="st">'l-functions'</span>,<span class="dv">10</span>,<span class="fl">5.5</span>)</span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(<span class="fu">list</span>(<span class="at">params=</span>params,<span class="at">summary=</span>summary,<span class="at">curves=</span>curves),<span class="st">'data/processed/results.rds'</span>)</span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a><span class="fu">writeLines</span>(<span class="fu">capture.output</span>(<span class="fu">sessionInfo</span>()),<span class="st">'_workflow/session-info.txt'</span>)</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'CP4B saved</span><span class="sc">\n</span><span class="st">'</span>);<span class="fu">print</span>(curves[curves<span class="sc">$</span>r <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">5</span>,<span class="dv">10</span>),])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="software-versions" class="level3" data-number="9.3">
<h3 data-number="9.3" class="anchored" data-anchor-id="software-versions"><span class="header-section-number">9.3</span> Software versions</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.6.1 (2026-06-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 26200)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] C
system code page: 65001

time zone: Asia/Singapore
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spatstat.explore_3.8-2 nlme_3.1-169           spatstat.random_3.5-1 
[4] ggplot2_4.0.3          spatstat.geom_3.8-2    spatstat.univar_3.2-0 
[7] spatstat.data_3.1-9    dplyr_1.2.1            sf_1.1-2              

loaded via a namespace (and not attached):
 [1] s2_1.1.11             generics_0.1.4        class_7.3-23         
 [4] tensor_1.5.1          KernSmooth_2.23-26    lattice_0.22-9       
 [7] digest_0.6.39         magrittr_2.0.5        spatstat.utils_3.2-4 
[10] evaluate_1.0.5        grid_4.6.1            RColorBrewer_1.1-3   
[13] fastmap_1.2.0         jsonlite_2.0.0        Matrix_1.7-5         
[16] spatstat.sparse_3.2-0 e1071_1.7-17          DBI_1.3.0            
[19] viridisLite_0.4.3     scales_1.4.0          textshaping_1.0.5    
[22] abind_1.4-8           cli_3.6.6             rlang_1.3.0          
[25] units_1.0-1           polyclip_1.10-7       withr_3.0.3          
[28] yaml_2.3.12           otel_0.2.0            tools_4.6.1          
[31] deldir_2.0-4          vctrs_0.7.3           R6_2.6.1             
[34] proxy_0.4-29          lifecycle_1.0.5       classInt_0.4-11      
[37] htmlwidgets_1.6.4     ragg_1.5.2            pkgconfig_2.0.3      
[40] pillar_1.11.1         gtable_0.3.6          glue_1.8.1           
[43] Rcpp_1.1.2            systemfonts_1.3.2     xfun_0.60            
[46] tibble_3.3.1          tidyselect_1.2.1      knitr_1.51           
[49] goftest_1.2-3         farver_2.1.2          htmltools_0.5.9      
[52] labeling_0.4.3        rmarkdown_2.31        wk_0.9.5             
[55] compiler_4.6.1        S7_0.2.2             </code></pre>
</div>
</div>
</section>
</section>
<section id="references" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="references"><span class="header-section-number">10</span> References</h2>
<ul>
<li><a href="https://isss626-ay2026-27aug.netlify.app/take-home_ex01">ISSS626 Take-home Exercise 1 requirements</a>.</li>
<li><a href="https://firms.modaps.eosdis.nasa.gov/download/Readme.txt">NASA FIRMS download documentation and disclaimer</a>. Request 804686, received September 2026.</li>
<li><a href="https://www.earthdata.nasa.gov/s3fs-public/2024-07/VIIRS_C2_AF-375m_User_Guide_1.0.pdf">NASA VIIRS Collection 2 Active Fire User Guide</a>.</li>
<li><a href="https://forum.earthdata.nasa.gov/viewtopic.php?t=5182">NASA guidance on detection confidence</a>.</li>
<li><a href="https://geoservices.big.go.id/rbi/rest/services/BATASWILAYAH/BATAS_WILAYAH/MapServer/13">BIG administrative boundary polygon service, layer 13</a>, Kapuas object 526, metadata dated 5 September 2024.</li>
<li><a href="https://www.indonesia-geospasial.com/2023/05/download-shapefile-batas-administrasi.html">Assignment-linked administrative boundary source</a>.</li>
<li><a href="https://spatstat.org/">spatstat project and documentation</a>, with installed R help for the functions used above.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>